Create filesystem on /dev/sda array

diff --git a/scripts/drive-prep b/scripts/drive-prep
--- a/scripts/drive-prep
+++ b/scripts/drive-prep
@@ -6,16 +6,37 @@ if [[ -e /dev/sdb ]]; then
 Your drives are not set to RAID 1 mode.
 Power down your CloudShell 2, adjust the dip switch,
 then hold the RAID Setup key for 30 seconds while powering up."
-  exit
+  exit 0
 fi
 
 if [[ -e /dev/sda ]]; then
   if [[ -e /dev/sda1 ]]; then
     echo "*********************************
-***           ERROR           ***
+***          WARNING          ***
 *********************************
-Your disk array contains partitions.
-Please remove the partitions and try again."
-    exit
+Your disk array already contains partitions / data.
+
+If you proceed, all data on your disk array will be lost.
+"
+    read -r -p "Do you want to destroy the array and re-initialize? [y/N] " beta
+    echo ""
+    if [[ $beta =~ ^([yY][eE][sS]|[yY])$ ]]; then
+      echo "Proceeding..."
+      # Instantly destory all partitions on /dev/sda
+      dd if=/dev/zero of=/dev/sda bs=512 count=1 > /dev/null 2>&1
+    else
+      echo "Aborted."
+      exit 1
+    fi
+
   fi
+else
+  echo "You do not have a RAID 1 configured. Please fix and try again."
+  exit 0
 fi
+
+# Create /dev/sda1 partition using entire size of array
+echo 'type=83' | sfdisk /dev/sda > /dev/null 2>&1
+
+# Create filesystem on /dev/sda1
+yes | mkfs.ext3 /dev/sda1
